Introduction
From the mix of greater global internet connectivity and the evolution of social networks, the shared economy has evolved providing buyers and sellers with platforms to transact business efficiently. Companies such as Airbnb, Lyft, and Uber have deployed peer-to-peer business models, which drives an economy characterized by collaborative consumption of goods and services, and shared value. 

Founded in 2008, Airbnb is a peer-to-peer network for hosts with extra space, rooms, or entire homes to rent to guests on a short-term basis. With over 150 million total users, 6 million listings worldwide, more than the 'top five' major hotel brands combined, and accommodating over 2 million guests per night, Airbnb has a market capitalization of over \$35 billion dollars as of January 2020 and is operating in over 190 countries. 

What's rather remarkable is that the Airbnb business model is not conceptually new, innovative, or unique to Airbnb. Rather than deliver the services directly, Airbnb delivers value by providing hosts with a convenient trading platform in which they earn extra income in the form of rent. Guests are offered a unique and cost effective alternative to traditional accommodations and a robust peer-to-peer review and verification system in which guests and hosts can choose those with whom they wish to transact. Depending upon the size of the reservation, guests pay a 6%-12% non-refundable service fee and hosts are also charged a 3% fee on each transaction.  

Yet, Airbnb is already a billion dollar company. To continue to grow, they must continue to evolve and adapt the business model to meet and overcome three key challenges. 

1. Demand and Supply Generation. First, peer-to-peer networks require a critical mass of hosts to provide the accommodations (supply-side) and guests to consume the market availability (demand-side). Whereas traditional hotels control supply through carefully planned development projects based upon market demand, Airbnb must entice hosts with the promise of additional income just as they must attract travellers seeking an authentic, unique and local experience to the network.

2. Trust, or trustworthiness, tightly linked to security, are essential components of the Airbnb model. Hosts must trust that guests will be good stewards of the properties that they rent. Similarly, guests must have confidence that the platform, its members, and the behaviors are consistent with expectations of a satisfying travel experience.  




# Background
In 2007, shortly after moving to San Francisco, two roommates, Brian Chesky and Joe Gebbia, came to an uncomfortable realization. It had become clear that, failing some intervention, they would not be able to make rent at the end of the month. Apparently, eviction is frowned upon by millenials. 

Coincidently, San Francisco was hosting an industrial design conference, selling out the inventory of hotels in the city. Brian and Joe saw this as an opportunity and decided that, for the ill-fated conference goers who were too late to find hotel accommodations, they would transform their living room and three air mattresses into a bed-n-breakfast. Nightly accommodations? Eight dollars per person! 

At that moment, the idea was cast. An idea, not unlike the ideas of scores of Silicon Valley entrepreneurs, but an idea that combined millenial tech sophistication, innate social media savvy, and fortuitous timing, possibly setting the pre-conditions for the kind of disruption foretold to us by internet celestials such as Gordon Moore, Marc Andreessen, Geoffrey Moore, and others. Brian and Joe approached their former roommate, Nathan Blecharczyk to do that which one does in San Francisco. Build a website!  Would it be Facebook or Friendster? 

In 2008, the website launched and no one noticed. So, they decided to launch again at the annual SxSW event. Five days later, they had two customers and Chesky was one of them. Fund raising was turning out to be an infertile endeavor. Rejected outright by not less than 15 investors, the team planned an offline marketing campaign during the Democratic National Convention in Denver. They fabricated promotional packs from cereal boxes, 800 of which they sold for $40 each, generating \$20,000, the company's seed cash.

The founders were not without some particle of progress. Paul Graham, co-founder of startup accelerator and seed capital firm, Y Combinator, dropped $20,000 and invited the team to join Y Combinator's 2009 batch. Unfortunately, the team struggled to convince other investors that their venture would develop into a profitable business. Weekly revenues were at \$200, they had no visibility, no growth prospects and no cash. As Gabbia would put it, the team was in the 'trough of sorrow'.

The Airbnb founders were also beset by legal and regulatory challenges as municipalities adopted an increasingly unwelcome stance towards the startup. Planners and city administrators would ultimately blaim Airbnb in part, for increasing rents and housing shortages. A prolonged legal dispute with the New York attorney general, characterized the relationships that Airbnb had with a growing number of municipalities. New laws in New York, where over 70% of all rentals are considered illegal, prohibited short-term rentals (less than 30 days) unless the owner also lived in the property. New York and San Francisco officials claim hosts are tax cheats. In New York, hosts are required to register with the city's Planning Department; pay a hotel tax; carry liability insurance and limit short-term rentals of entire-home to 90 days per year. San Francisco, New Orleans, Malibu and other US cities were mounting crackdowns. Regular short-term letting of rooms required authorization. Protesters in San Francisco demonstrated over evictions caused by landlords converting buildings to Airbnb units.


>>Luck is not chance, it's toil; fortune's expensive smile is earned.
                                                                Emily Dickinson
                                                                
Finally, the harried trio who struggled so magnificently in 2008, managed to raise $150K and picked up another \$600K of seed funding from Greylock Partners and Sequoia Capital in April 2009. Flight attendants, prepare for take-off. Andreessen Horowitz dropped \$7.2M in Series A funding and another, wait for it..., \$112M, bringing Airbnb's valuation to about \$1B. In April of 2015, the company closed on an investment of \$450M by TPG Capital. An addition \$1.5B in Series E funding was raised, led by y General Atlantic, and joined by Hillhouse Capital Group, Tiger Management, Kleiner Perkins Caufield & Byers, GGV Capital, China Broadband Capital, and Horizons Ventures. In September 2016, the company raised \$555.5M in funding from Google Capital and Technology Crossover Ventures, valuing the company at \$30B. Please place seat backs and tray tables in their full upright and locked position. Airbnb was Silicon Valley Mythology!

In February 2011, Airbnb announced its 1,000,000th night booked, in January 2012, they released notice of their 5,000,000th booking. By June, they had clocked their 10,000,000th night booked. Of which, 75% of the business came from markets outside the continential United States. They opened offices in Paris, Milan, Barcelona, Copenhagen, Moscow and Sao Paulo in addition to their existing offices in San Francisco, New York, London, Hamburg, and Berlin.

In 2014, investors like Fred Wilson, co-founder of Union Square Ventures, were replete with regret. Airbnb's cereal box that the Union Square guys purchased from Chesky and team back in Denver for $40, remains in the Union Square Venture's main conference room as a reminder of bad decisions and missed opportunity. Because, in 2014, Airbnb had an estimated valuation of \$10B.

Airbnb reached profitability in 2016, in which revenue grew by more than 80%. Today, Airbnb has over 150M users and over 2M guests per night. Global listings exceed 6M and there are over 650,000 hosts worldwide generating over \$100M in annual profit. The current global valuation is over $35B.

